server:
  address: http://fogbugz # Can be any URL, use HTTPS when possible

user:
  email: test@test.com
  password: testpass

output:
  progress: true
  colorize: true

cases:
  default_columns: "ixBug,ixBugParent,ixBugChildren,fOpen,sTitle,sPersonAssignedTo,sEmailAssignedTo,sStatus"